#pragma once

#include <windows.h>
#include <ShlObj_core.h>
#include <shlwapi.h>

#include "ResultUtils.h"

template <class T>
void SafeRelease(__deref_inout_opt T **ppT)
{
	T *pTTemp = *ppT; // temp copy
	*ppT = nullptr;   // zero the input
	if (pTTemp)
	{
		pTTemp->Release();
	}
}

MIDL_INTERFACE("E1F5EC9F-F933-492B-A242-C3CDAC6ECFBD")
IDUIElementProviderInit: public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE SetResourceID(UINT uID) = 0;
	virtual HRESULT STDMETHODCALLTYPE OptionallyTakeInitialFocus(BOOL *pbTookFocus) = 0;
};

MIDL_INTERFACE("1D3293BC-EC01-400F-8179-8DE5D53ABEB7")
IFrameNotificationClient : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE LayoutInitialized() = 0;
	virtual HRESULT STDMETHODCALLTYPE Notify(LPCWSTR pszChangedProp) = 0;
	virtual HRESULT STDMETHODCALLTYPE OnNavigateAway() = 0;
	virtual HRESULT STDMETHODCALLTYPE OnInnerElementDestroyed() = 0;
};

MIDL_INTERFACE("6B353825-C58B-4F03-AEC4-8DE179122661")
IFrameShellViewClient : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE OnSelectedItemChanged() = 0;
	virtual HRESULT STDMETHODCALLTYPE OnSelectionChanged() = 0;
	virtual HRESULT STDMETHODCALLTYPE OnContentsChanged() = 0;
	virtual HRESULT STDMETHODCALLTYPE OnFolderChanged() = 0;
};

enum CPNAV_LIST : int
{
	CPNAV_LIST_TASKS = 0,
	CPNAV_LIST_SEEALSO = 1,
};

enum CPNAV_CMDTYPE : int
{
	CPNAV_CMDTYPE_NOTIFY = 0,
	CPNAV_CMDTYPE_SHELLEX = 1,
	CPNAV_CMDTYPE_CONTROLPANEL = 2,
};

MIDL_INTERFACE("6FABDA16-031E-47E3-B2A2-2339C05CCB9E")
IMultiObjectElevationFactory : public IUnknown
{
public:
	virtual HRESULT STDMETHODCALLTYPE Initialize(HWND hwnd, GUID param) = 0;
	virtual HRESULT STDMETHODCALLTYPE InitializeNoWaitCursor(HWND hwnd, GUID param) = 0;
	virtual HRESULT STDMETHODCALLTYPE CreateElevatedObject(GUID param, GUID param2, void **ppv) = 0;
};

typedef enum tagLAYOUTTYPE
{
	LAYOUTTYPE_LEGACYSHELLVIEW = 0,
	LAYOUTTYPE_NORMAL = 1,
	LAYOUTTYPE_SEARCHPAGE = 2,
	LAYOUTTYPE_CONTROLPANEL = 3,
	LAYOUTTYPE_CONTROLPANELHOME = 4,
	LAYOUTTYPE_PHOTO = 5,
	LAYOUTTYPE_MUSIC = 6,
	LAYOUTTYPE_DOCUMENTS = 7,
	LAYOUTTYPE_SOFTWAREEXP = 8,
	LAYOUTTYPE_NOPREVIEW = 9,
	LAYOUTTYPE_GAMEEXPLORER = 10,
	LAYOUTTYPE_COMPUTER = 11,
	LAYOUTTYPE_USEROOBE = 12,
	LAYOUTTYPE_EMAIL = 13,
	LAYOUTTYPE_CONTACTS = 14,
	LAYOUTTYPE_CHGREMOVEAPP = 15,
	LAYOUTTYPE_APPUPDATE = 16,
	LAYOUTTYPE_ADDNEWAPP = 17,
	LAYOUTTYPE_SYNCCENTER = 18,
	LAYOUTTYPE_SEARCHONLYBARRIER = 19,
	LAYOUTTYPE_EMPTYLIBRARYBARRIER = 20,
	LAYOUTTYPE_HGCREATEBARRIER = 21,
	LAYOUTTYPE_HGJOINBARRIER = 22,
	LAYOUTTYPE_HGMERGEBARRIER = 23,
	LAYOUTTYPE_HGPASSWORDBARRIER = 24,
	LAYOUTTYPE_HGONLYMEMBERBARRIER = 25,
	LAYOUTTYPE_HGAUTOCREATEDBARRIER = 26,
	LAYOUTTYPE_HGEMPTYNODEBARRIER = 27,
	LAYOUTTYPE_HGOFFLINEMACHINE = 28,
} LAYOUTTYPE;

MIDL_INTERFACE("50F4AA22-3684-4837-AB29-9485F697A0D1")
ILayoutType : IUnknown
{
	STDMETHOD(GetLayoutType)(LAYOUTTYPE *) PURE;
};

MIDL_INTERFACE("31E4FA78-02B4-419F-9430-7B7585237C77")
IFrameManager : ILayoutType
{
	STDMETHOD(GetShellView)(IShellView **) PURE;
	STDMETHOD(GetPersistStream)(int, LPCWSTR, LPCWSTR, ULONG, IStream **) PURE;
};

enum SEARCHTARGETFLAGS
{
	STF_DEFAULT = 0x0,
	STF_NAVIGATETOSEARCH = 0x1,
};

DEFINE_ENUM_FLAG_OPERATORS(SEARCHTARGETFLAGS)

MIDL_INTERFACE("DDA3A58A-43DA-4A43-A5F2-F7ABF6E3C026")
IShellSearchTargetServices : IUnknown
{
	STDMETHOD(GetPromptText)(LPWSTR, UINT) PURE;
	STDMETHOD(GetTargetFlags)(SEARCHTARGETFLAGS, SEARCHTARGETFLAGS *) PURE;
};

enum SSCSTATEFLAGS
{
	SSCSTATE_DEFAULT = 0x1,
	SSCSTATE_NOSETFOCUS = 0x2,
	SSCSTATE_DRAWCUETEXTFOCUS = 0x4,
	SSCSTATE_APPENDTEXT = 0x8,
	SSCSTATE_COMMIT = 0x10,
	SSCSTATE_NODROPDOWN = 0x20,
	SSCSTATE_DISABLED = 0x40,
	SSCSTATE_NOSUGGESTIONS = 0x80,
	SSCSTATE_STRUCTUREDQUERYPARSING = 0x100,
};

DEFINE_ENUM_FLAG_OPERATORS(SSCSTATEFLAGS);

enum SEARCH_BOX_SUGGEST_POPUP_SETTING
{
	SBSPS_DEFAULT = 0x0,
	SBSPS_NO_POPUP = 0x1,
	SBSPS_CUSTOM_MRU = 0x2,
	SBSPS_POPUP_ON_TEXT = 0x4,
	SBSPS_ONLY_MRU = 0x8,
	SBSPS_DRAWCUETEXTFOCUS = 0x10,
};

DEFINE_ENUM_FLAG_OPERATORS(SEARCH_BOX_SUGGEST_POPUP_SETTING);

enum SSC_WIDTH_FLAGS
{
	SSCWIDTH_DEFAULT = 0x0,
	SSCWIDTH_SETBYUSER = 0x1,
};

DEFINE_ENUM_FLAG_OPERATORS(SSC_WIDTH_FLAGS);

enum SSCTEXTFLAGS
{
	SSCTEXT_DEFAULT = 0x0,
	SSCTEXT_TAKEFOCUS = 0x1,
	SSCTEXT_FORCE = 0x2,
	SSCTEXT_CLEARAUTONAVIGATE = 0x4,
};

DEFINE_ENUM_FLAG_OPERATORS(SSCTEXTFLAGS);

MIDL_INTERFACE("111F7C32-0546-4227-8B7F-C53A0B114A0F")
IShellSearchControl : IUnknown
{
	STDMETHOD(Initialize)(HWND, const RECT *) PURE;
	STDMETHOD(SetFlags)(SSCSTATEFLAGS) PURE;
	STDMETHOD(SetPopupFlags)(SEARCH_BOX_SUGGEST_POPUP_SETTING) PURE;
	STDMETHOD(GetFlags)(SSCSTATEFLAGS *) PURE;
	STDMETHOD(SetMRULocation)(REFGUID) PURE;
	STDMETHOD(SetCueAndTooltipText)(LPCWSTR, LPCWSTR) PURE;
	STDMETHOD(SetLocation)(IShellItem *) PURE;
	STDMETHOD(GetDesiredSize)(SIZE *) PURE;
	STDMETHOD(UpdateWidth)(int, SSC_WIDTH_FLAGS) PURE;
	STDMETHOD(GetText)(LPWSTR, UINT) PURE;
	STDMETHOD(SetText)(LPCWSTR, SSCTEXTFLAGS) PURE;
	STDMETHOD(DoesEditBoxHaveFocus)(BOOL *) PURE;
	STDMETHOD(HasSuggestions)() PURE;
	STDMETHOD(HideSuggestions)() PURE;
	STDMETHOD(KillSelection)() PURE;
};

HRESULT WINAPI IUnknown_ProfferService(IUnknown *punkSite, REFGUID sidWhat, IServiceProvider *pService, DWORD *pdwCookie);
HRESULT WINAPI IUnknown_QueryServiceForWebBrowserApp(IUnknown *punk, REFIID riid, LPVOID *ppvOut);

STDAPI_(BOOL) SHIsChildOrSelf(HWND hwndParent, HWND hwnd);